export const infoIcon: string
export const progressIcon: string
export const spin: string
export const progressIconLight: string
export const progressIconSm: string
export const progressIconLg: string
export const socialIcon: string
export const btnIcon: string
export const accountIcon: string
export const settingsIcon: string
export const backIcon: string
