export const modal: string
export const modalChild: string
export const modalOverlay: string
export const daiColor: string
export const errorColor: string
export const tokenIcon: string
export const hrMargin: string
export const dict: string
export const dictName: string
export const dictDescription: string
export const dictDescriptionMainFont: string
export const inputGroup: string
export const input: string
export const inputCurrencyAddon: string
export const buttons: string
export const button: string
export const finalizeMarginable: string
export const superSmallFont: string
export const green: string
export const spaceLeft: string
export const tokenDescriptionLine: string
export const hideDoubleHr: string
