name: Build and Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node Version
        uses: actions/setup-node@v1
        with:
          node-version: '10.19'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Install depenencies
        run: yarn --frozen-lockfile

      - name: Run Tests
        run: CI=true yarn test
